### PR TITLE
Added unit test manager

### PR DESCRIPTION
**Pull request by bocajnotnef**
TODO:

 - [x] convert the remaining UTests to Catch tests
 - [x] add test maketarget to master Makefile
 - [ ] ~~add diff-cover maketarget to loudly complain about differences in coverage~~
 - [x] Add docs on writing tests
 - [ ] ~~Squash all the things~~

~~Not ready for merge.~~

Technically depends on #10 
Addresses #1

### CODE REVIEW

**Comment by bocajnotnef** [comment]
Current progress: Have migrated all of `utests/tools/*` to catch.

Now we just have to do the rest (ugh)

**Comment by bocajnotnef** [comment]
Current coverage stats:

capture

**Comment by bocajnotnef** [comment]
Also ran into a bad test with geometry:

```
REQUIRE(body1.CalcPressure() == 32);
```
CalcPressure doesn't exist.

Additionally,
```
REQUIRE(circle0.HasOverlap(circle_big) == false)
```
This is apparently True

**Comment by bocajnotnef** [comment]
Author class was missing the constructor for only being given a last name; I added it.

**Comment by bocajnotnef** [comment]
- [ ] Change test maketarget to not run coverage things, make coverage run coverage things

**Comment by bocajnotnef** [comment]
- [ ] document dependencies (g++, lcov, gcov)

**Comment by mercere99** [comment]
Hrrrm...  maybe I'm not understanding what it means by "Line Coverage" vs. "Function Coverage".  How can you have 100% Line Coverage, but less than 100% Function Coverage?  More generally, some of those look better covered than I would have ever expected.  ;-)

**Comment by bocajnotnef** [comment]
Looks like that's where the coverage metrics run afoul of the
#ifdef/#define blocks. I'll have to experiment some.

One thing to keep track of is that though the code is covered it doesn't
necessarily have asserts keeping track of what it does--so we know it
doesn't explode when compiled/run, but we don't know if it runs *correctly*

But that's true of nearly all testing setups.

**Comment by bocajnotnef** [comment]
dependency: gcovr 
https://github.com/gcovr/gcovr/releases

**Comment by bocajnotnef** [comment]
Alright, current difficulty: finding a good way to see if test coverage has dropped/changed/code was added that's not covered.

That might be an issue I just table for now and hammer on later.

**Comment by bocajnotnef** [comment]
@mercere99 Ready for merge at your leisure

**Comment by bocajnotnef** [comment]
(the 12k deleted files are from where I forgot to not include the doc/build directory in commits and I deleted them, if you're wondering. gitignore and make clean have been updated accordingly)

**Pull request merged**
