### PR TITLE
Feature/doxygen: doxygen/breathe/sphinx autodoc system

### PR DESCRIPTION
**Pull request by bocajnotnef**
Not yet ready for merge, but open to suggestions/commentary

See also #9 re: dependencies//installation lumps

TODO:
 - [x] Document installing dependencies to make documentation (to understand recursion...)
 - [x] Reserve empirical.readthedocs.org (if agreeable with @mercere99)
 - [x] Make automated Doxygen/etc build maketarget (e.g. `make build-dep`)

### CODE REVIEW

**Comment by bocajnotnef** [comment]
TODO:
 - [ ] Decide on actual CR process (e.g. who has merge authority, not overloading @mercere99, do we even think this'll be an issue for now?)

**Comment by bocajnotnef** [comment]
TODO:
 - [ ] add maketargets mentioned in a57342c0bdefc9fbe016b8cedd881d834d39eaa9

**Comment by mercere99** [comment]
empirical.readthedocs.org sounds like a good plan to me.

**Comment by bocajnotnef** [comment]
- [ ] s/khmer/empirical/g

**Comment by bocajnotnef** [comment]
- [ ] fix readthedocs stuff

**Comment by bocajnotnef** [comment]
@mercere99 Should be ready for merge. I can't test readthedocs more until this is merged into master.

things you should definitely look at: the `.rst` files in `doc/dev` and `doc/user`--everything else is pretty much configuration/implementation.

**Comment by bocajnotnef** [comment]
Probably to-do:

- [ ] document doxygen style comments, so we can actually use the system

**Comment by bocajnotnef** [comment]
So, did some hammering on the doc structure and explored the [various directives available](https://breathe.readthedocs.org/en/latest/directives.html#doxygenfil) to get a feel for how the docs look.

I figure there's a couple options that make sense. We could break down the docs on a by-module level, so we'd have docs for 'tools' and docs for 'scholar' and docs for 'web' and whathaveyou, and each module-level of documentaiton would have a breakdown of the files within that module. So it'd look something like this;
screenshot from 2015-11-04 11-30-25

The downside here is I'm not sure we'd want to have it be on a by-file layout since then all the defines and such are visible (though I think it's possible to suppress them). It may be possible to do the docs on a by-funciton or by-namespace layout--the downside there is that we'd then have to create a directive for every individual function, or if we did a namespace it'd just look terribly messy:
screenshot from 2015-11-04 11-34-32

for now I think a by-module breakdown with file-based directives would work rather nicely.

I've pushed up an example that shows a couple of the files from the 'tools' module alongside the full namespace breakdown.

@mercere99 Thoughts?

**Comment by mercere99** [comment]
Is it possible to setup the docs on a per-file basis instead of per folder?  I'm not sure which way would be best, but some of the folders (like tools) will have a TON of functions and classes in them.  Of course, there are also a lot of files; is more of a hierarchy possible?

Since everything is in the emp namespace, I don't think per-namespace makes sense.

We should talk about how we need to structure the docs in the code for them to be extracted most cleanly.

**Comment by bocajnotnef** [comment]
Yeah, we can do it per-file. That's actually fairly easy to do, and kind of
what I meant--there's no way to actually do it on a per-module basis within
sphyinx, but we could make a landing page for each module in the docs,
detail what they're for and then have it display the breakdown of the files.

Might be easier to show you, which I'll do tomorrow morning.

The in-code documentation structure is surprisingly easy to get a handle
on. I'll write up a doc on how to do the docs and include it.

**Comment by mercere99** [comment]
This all sounds like a great plan then.

**Pull request merged**
